name: Rails Tests

on:
  - push
  - pull_request

env:
  RUBY_VERSION: 3.1.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Install JavaScript dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Run tests
        run: bundle exec rspec .

      - name: Run Brakeman security scan
        run: brakeman -o brakeman.txt

      - name: Run RuboCop
        run: bundle exec rubocop --force-exclusion --out rubocop.txt

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage

      - name: Upload RuboCop report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rubocop-report
          path: rubocop.txt

      - name: Upload Brakeman report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: brakeman-report
          path: brakeman.txt
